apiVersion: skaffold/v2beta6
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: springcloudservices/animal-rescue-k8s
    context: backend
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base-platform-api-latest
      dependencies:
        paths:
        - src
        - build.gradle
  - image: springcloudservices/animal-rescue-partner
    context: external-api
    buildpacks:
      builder: gcr.io/paketo-buildpacks/builder:base-platform-api-latest
      dependencies:
        paths:
        - .
        ignore:
        - node_modules
deploy:
  kustomize:
    paths:
    - backend/k8s/
    - external-api/k8s/
    - k8s
  helm:
    flags:
      install: [ "--create-namespace" ]
    releases:
      - name: oauth2-proxy-internal
        chartPath: stable/oauth2-proxy
        valuesFiles: [k8s/internal-oauth2-proxy-helm-values.yaml]
        remote: true
        namespace: animal-rescue

      - name: oauth2-proxy-external
        chartPath: stable/oauth2-proxy
        valuesFiles: [k8s/external-oauth2-proxy-helm-values.yaml]
        remote: true
        namespace: animal-rescue
