apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: animal-rescue
secretGenerator:
- name: oauth2-external-proxy-creds-kubedemo
  envs:
  - secret/oauth2-external-proxy-creds-kubedemo
  type: Opaque
- name: oauth2-internal-proxy-creds
  envs:
  - secret/oauth2-internal-proxy-creds
  type: Opaque
- name: ingress-basic-auth
  type: Opaque
  files:
  - auth
- name: clouddns-dns01-solver-svc-acct
  type: Opaque
  files:
  - secret/credentials.json
  namespace: external-dns
generatorOptions:
  disableNameSuffixHash: true
resources:
- animal-rescue-external-ingress.yaml
- animal-rescue-internal-ingress.yaml
- letsencrypt-staging.yaml
