apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
secretGenerator:
- name: oauth2-external-proxy-creds-kubedemo
  envs:
  - secret/oauth2-external-proxy-creds-kubedemo
  type: Opaque
  namespace: external-dns
- name: oauth2-internal-proxy-creds
  envs:
  - secret/oauth2-internal-proxy-creds
  type: Opaque
  namespace: external-dns
generatorOptions:
  disableNameSuffixHash: true
